### ISSUE TITLE
DHT22 program stop

### ISSUE THREAD

**Issue by saeed14473** [adafruit/DHT-sensor-library#173]
Hi
I'm using stm32f103c8t6.
when dht22 sensor is present humidity and temperature calculate correctly.
but when I de attach sensor , program stop in beginning of read function.
Where is my problem?

**Comment by siddacious** [comment]
when you say "I de attach sensor" do you mean you disconnect the sensor while the program is running? If so, this is expected behavior because the program is trying to talk to the sensor that isn't there any more.

If this is not what you mean, please give more details  including the exact sequence of events.
