### ISSUE TITLE
DHT not recognized

### ISSUE THREAD

**Issue by ghost** [adafruit/DHT-sensor-library#23]
I'm getting this and I don't know how to resolve this. If someone could help me I'd appreciate it. 
DHTtester.ino:4:17: error: DHT.h: No such file or directory
DHTtester:18: error: 'DHT' does not name a type
DHTtester.ino: In function 'void setup()':
DHTtester:24: error: 'dht' was not declared in this scope
DHTtester.ino: In function 'void loop()':
DHTtester:33: error: 'dht' was not declared in this scope

**Comment by 713908** [comment]
You need to add DHT Library to Arduino IDE:
Sketch / Include Library / Add .Zip Library,
here u r :  https://github.com/adafruit/DHT-sensor-library

**Comment by marimic** [comment]
I am having this problem now out of the blue when all my code was working fine before and Arduino recognized the library. I am copying and pasting parts of the original code into a new sketch but I don't see why or where the problem is. So I went to several sketches that I KNOW worked fine and now i get the same error message - DHT11 not is this scope. Now none of my previously perfectly functioning sketches work. I know this thread is old, but it anyone has any idea...please share. thx!

**Comment by marimic** [comment]
Problem fixed. I had a second library called DHT. Arduino was getting confused. Must've downloaded the second library with a bunch of others.

**Comment by krishna1703** [comment]
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

fhfhfh:11: error: 'dht' does not name a type

 dht DHT;

 ^

C:\Users\krishna\Documents\Arduino\fhfhfh\fhfhfh.ino: In function 'void loop()':

fhfhfh:55: error: expected unqualified-id before '.' token

   DHT.read11(dht_dpin);

      ^

fhfhfh:58: error: expected primary-expression before '.' token

   humi=DHT.humidity;

           ^

fhfhfh:63: error: expected primary-expression before '.' token

   tem=DHT.temperature;

          ^

exit status 1
'dht' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


i got this type of error. please help me to solve this error

**Comment by marimic** [comment]
You need to import the dht library for Arduino. Go here: https://github.com/adafruit/DHT-sensor-library

**Comment by siva2344** [comment]
while running the code it is showing

In file included from C:\Users\Dinesh\Documents\Arduino\sketch_sep30c\sketch_sep30c.ino:1:0:

C:\Users\Dinesh\Documents\Arduino\libraries\Adafruit-PCD8544-Nokia-5110-LCD-library-master/Adafruit_PCD8544.h:69:46: error: expected class-name before '{' token

 class Adafruit_PCD8544 : public Adafruit_GFX {

                                              ^

sketch_sep30c:13:17: error: 'DHT_11' was not declared in this scope

 #define DHTTYPE DHT_11   // DHT 11

                 ^

C:\Users\Dinesh\Documents\Arduino\sketch_sep30c\sketch_sep30c.ino:16:20: note: in expansion of macro 'DHTTYPE'

 DHT dht(DHT11_PIN, DHTTYPE);

                    ^

C:\Users\Dinesh\Documents\Arduino\sketch_sep30c\sketch_sep30c.ino: In function 'void setup()':

sketch_sep30c:40:7: error: 'class DHT' has no member named 'begin'

   dht.begin();

       ^

C:\Users\Dinesh\Documents\Arduino\sketch_sep30c\sketch_sep30c.ino: In function 'void digitalDisplay()':

sketch_sep30c:82:16: error: 'class DHT' has no member named 'readTemperature'

     Temp = dht.readTemperature();

                ^

sketch_sep30c:83:16: error: 'class DHT' has no member named 'readHumidity'

     Humi = dht.readHumidity();

                ^

sketch_sep30c:86:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(1);

             ^

sketch_sep30c:88:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(0, 0);

             ^

sketch_sep30c:89:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(contrast);

             ^

sketch_sep30c:90:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(24, 0);

             ^

sketch_sep30c:91:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(now.day(), DEC);

             ^

sketch_sep30c:92:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print('/');

             ^

sketch_sep30c:93:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(now.month(), DEC);

             ^

sketch_sep30c:94:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print('/');

             ^

sketch_sep30c:95:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(now.year(), DEC);

             ^

sketch_sep30c:96:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(72, 20);

             ^

sketch_sep30c:98:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(2);

             ^

sketch_sep30c:99:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(10, 14);

             ^

sketch_sep30c:101:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(':');

             ^

sketch_sep30c:103:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(0, 32);

             ^

sketch_sep30c:104:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(1);

             ^

sketch_sep30c:105:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print("T");

             ^

sketch_sep30c:106:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(6, 32);

             ^

sketch_sep30c:107:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(2);

             ^

sketch_sep30c:108:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(Temp);

             ^

sketch_sep30c:109:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print("c");

             ^

sketch_sep30c:110:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(42, 32);

             ^

sketch_sep30c:111:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(1);

             ^

sketch_sep30c:112:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print("H");

             ^

sketch_sep30c:113:13: error: 'class Adafruit_PCD8544' has no member named 'setCursor'

     display.setCursor(48, 32);

             ^

sketch_sep30c:114:13: error: 'class Adafruit_PCD8544' has no member named 'setTextSize'

     display.setTextSize(2);

             ^

sketch_sep30c:115:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print(Humi);

             ^

sketch_sep30c:116:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print("%");

             ^

C:\Users\Dinesh\Documents\Arduino\sketch_sep30c\sketch_sep30c.ino: In function 'void printDigits(int)':

sketch_sep30c:123:13: error: 'class Adafruit_PCD8544' has no member named 'print'

     display.print('0');

             ^

sketch_sep30c:124:11: error: 'class Adafruit_PCD8544' has no member named 'print'

   display.print(digits);

           ^

sketch_sep30c:128:11: error: 'class Adafruit_PCD8544' has no member named 'print'

   display.print(digits);

           ^

**Comment by geofbaum** [comment]
@siva2344 What does your code actually look like because it seems like your file can't find the files that it's suppose to or things are not initialized properly. Also when you share your code can you please format the post properly so that the code is legible using Markdown or the insert code button.

**Comment by siva2344** [comment]
This is the actual code 
#include <Adafruit_GFX.h>
#include <Adafruit_PCD8544.h>
#include <Wire.h>         // this #include still required because the RTClib depends on it
#include "RTClib.h"
#include "DHT.h"
#define DHT11_PIN A0     // what pin we're connected to
#define DHTTYPE DHT11   // DHT 11
DHT dht(DHT11_PIN, DHTTYPE);
RTC_Millis rtc;
int contrast=50;
int Temp;
int Humi;
int umi=0;
int digits;
int digitt;
boolean light = true;
volatile boolean buttonA = false;
volatile boolean buttonB = false;
volatile boolean buttonC = false;
int StateOfbuttonA = 0;
int StateOfbuttonB = 0;  
int StateOfbuttonC = 0;        
int NewStateOfbuttonA = 0;        
int NewStateOfbuttonB = 0;        
int NewStateOfbuttonC = 0;  
int yearr = 2017;
int dayy = 1;  
int monthh = 1;          
int hourr = 0;        
int minutee = 0;     
int secondd = 0; 
Adafruit_PCD8544 display = Adafruit_PCD8544(7, 6, 5, 4, 3);


void setup() {
  pinMode(11, INPUT_PULLUP);
  pinMode(10, INPUT_PULLUP);
  pinMode(9, INPUT_PULLUP);
  pinMode(8,OUTPUT);
  digitalWrite(8,LOW); //Turn Backlight ON
  dht.begin();
  display.begin();      
  display.setContrast(contrast); //Set contrast to 50
  display.clearDisplay(); 
  display.display(); 
  rtc.begin(DateTime(F(__DATE__), F(__TIME__)));
}

void loop() {
  NewStateOfbuttonA = digitalRead(9);
  NewStateOfbuttonB = digitalRead(10);
  NewStateOfbuttonC =   digitalRead(11);
  buttonAisPressed();
  buttonBisPressed();
  buttonCisPressed();
   if (buttonA) {
   if (umi == 1 ) {
    buttonA = false;
    contrast++;
    setContrast();
    }      
  else if (umi == 2 ) {
    buttonA = false;
    yearr++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }    
  else if (umi == 3 ) {
    buttonA = false;
    monthh++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  } 
  else if (umi == 4 ) {
    buttonA = false;
    dayy++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }   
  else if (umi == 5 ) {
    buttonA = false;
    hourr++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 6 ) {
    buttonA = false;
    minutee++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 7 ) {
    buttonA = false;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,0));
  }
  else if (umi == 8 ) {
    buttonA = false;
  if (light) 
      {
        light = false;
        lightOff();
        }
      else 
      {
        light = true; 
        lightOn();
       }
}
       }
   if (buttonB) {
    buttonB = false;
      umi++;
      if (umi == 9 ) {
      umi = 0;
  }
    }
   if (buttonC) {
   if (umi == 1 ) {
    buttonC = false;
    contrast--;
    setContrast();
    }      
  else if (umi == 2 ) {
    buttonC = false;
    yearr--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }    
  else if (umi == 3 ) {
    buttonC = false;
    monthh--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  } 
  else if (umi == 4 ) {
    buttonC = false;
    dayy--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }   
  else if (umi == 5 ) {
    buttonC = false;
    hourr--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 6 ) {
    buttonC = false;
    minutee--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 7 ) {
    buttonC = false;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,0));
  }
  else if (umi == 8 ) {
    buttonC = false;
    if (light) 
      {
        light = false;
        lightOff();
        }
      else 
      {
        light = true; 
        lightOn();
       }
       }
  
   
}
     digitalDisplay();
}

void digitalDisplay(){
    Temp = dht.readTemperature();
    Humi = dht.readHumidity();
    DateTime now = rtc.now();
    
    printDigitt(now.year());
    yearr == digitt;
    printDigitt(now.month());
    dayy == digitt;
    printDigitt(now.day());
    monthh == digitt;
    printDigitt(now.hour());
    hourr == digitt;
    printDigitt(now.minute());
    minutee == digitt;
    printDigitt(now.second());
    secondd == digitt;
  // digital clock display of the time
    display.setTextSize(1);
    display.clearDisplay();
    if (umi == 1) 
      {
    display.setCursor(5, 0);
    display.print(contrast);
        }
    if (umi == 8) 
      {
    display.setCursor(7, 0);
    display.print("*");
        }
    display.setTextColor(BLACK, WHITE);
    display.setCursor(24, 0);
    if (umi == 2) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.year());
    display.setTextColor(BLACK, WHITE);
    display.print('/');
    if (umi == 3) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.month());
    display.setTextColor(BLACK, WHITE);
    display.print('/');
    if (umi == 4) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.day());
    if (umi == 7) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    display.setCursor(72, 20);
    printDigits(now.second());
    display.setTextSize(2);
    display.setCursor(10, 14);
    if (umi == 5) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.hour());
    display.setTextColor(BLACK, WHITE);
    display.print(':');
    if (umi == 6) 
      {
    display.setTextColor(WHITE, BLACK);
        }
      else 
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.minute());
    display.setTextColor(BLACK, WHITE);
    display.setCursor(0, 32);
    display.setTextSize(1);
    display.print("T");
    display.setCursor(6, 32);
    display.setTextSize(2);
    display.print(Temp);
    display.print("c");
    display.setCursor(42, 32);
    display.setTextSize(1);
    display.print("H");
    display.setCursor(48, 32);
    display.setTextSize(2);
    display.print(Humi);
    display.print("%");
    display.display();
}
void printDigits(int digits){
  // utility function for digital clock display: prints preceding colon and leading 0
  if(digits < 10){
    display.print('0');
  display.print(digits);
       }
      else 
      {
  display.print(digits);
       }
}



  void buttonAisPressed()
  {
    if (NewStateOfbuttonA != StateOfbuttonA) 
  {
    if (NewStateOfbuttonA == 0) 
    {
      buttonA=true;
    }
    delay(50);
  }
   StateOfbuttonA = NewStateOfbuttonA;
  }

void buttonBisPressed()
{
  if (NewStateOfbuttonB != StateOfbuttonB) 
  {
    if (NewStateOfbuttonB == 0) {
      buttonB=true;
    }
    delay(50);
  }
   StateOfbuttonB = NewStateOfbuttonB;
}

void buttonCisPressed()
{
   if (NewStateOfbuttonC != StateOfbuttonC) 
  {
    if (NewStateOfbuttonC == 0) {
      buttonC=true;
    }
    delay(50);
  }
   StateOfbuttonC = NewStateOfbuttonC;
}
void lightOn()
  {
    digitalWrite(8,LOW);
  }

    void lightOff()
  {
    digitalWrite(8,HIGH);
  }

  void setContrast()
  {
    display.setContrast(contrast);
    display.display();
  }
void printDigitt(int digitt){
    digitt == digitt;
       }

**Comment by siva2344** [comment]
Pls make this code to run

#include <Adafruit_GFX.h>
#include <Adafruit_PCD8544.h>
#include <Wire.h>         // this #include still required because the
RTClib depends on it
#include "RTClib.h"
#include "DHT.h"
#define DHT11_PIN A0     // what pin we're connected to
#define DHTTYPE DHT11   // DHT 11
DHT dht(DHT11_PIN, DHTTYPE);
RTC_Millis rtc;
int contrast=50;
int Temp;
int Humi;
int umi=0;
int digits;
int digitt;
boolean light = true;
volatile boolean buttonA = false;
volatile boolean buttonB = false;
volatile boolean buttonC = false;
int StateOfbuttonA = 0;
int StateOfbuttonB = 0;
int StateOfbuttonC = 0;
int NewStateOfbuttonA = 0;
int NewStateOfbuttonB = 0;
int NewStateOfbuttonC = 0;
int yearr = 2017;
int dayy = 1;
int monthh = 1;
int hourr = 0;
int minutee = 0;
int secondd = 0;
Adafruit_PCD8544 display = Adafruit_PCD8544(7, 6, 5, 4, 3);


void setup() {
  pinMode(11, INPUT_PULLUP);
  pinMode(10, INPUT_PULLUP);
  pinMode(9, INPUT_PULLUP);
  pinMode(8,OUTPUT);
  digitalWrite(8,LOW); //Turn Backlight ON
  dht.begin();
  display.begin();
  display.setContrast(contrast); //Set contrast to 50
  display.clearDisplay();
  display.display();
  rtc.begin(DateTime(F(__DATE__), F(__TIME__)));
}

void loop() {
  NewStateOfbuttonA = digitalRead(9);
  NewStateOfbuttonB = digitalRead(10);
  NewStateOfbuttonC =   digitalRead(11);
  buttonAisPressed();
  buttonBisPressed();
  buttonCisPressed();
   if (buttonA) {
   if (umi == 1 ) {
    buttonA = false;
    contrast++;
    setContrast();
    }
  else if (umi == 2 ) {
    buttonA = false;
    yearr++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 3 ) {
    buttonA = false;
    monthh++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 4 ) {
    buttonA = false;
    dayy++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 5 ) {
    buttonA = false;
    hourr++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 6 ) {
    buttonA = false;
    minutee++;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 7 ) {
    buttonA = false;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,0));
  }
  else if (umi == 8 ) {
    buttonA = false;
  if (light)
      {
        light = false;
        lightOff();
        }
      else
      {
        light = true;
        lightOn();
       }
}
       }
   if (buttonB) {
    buttonB = false;
      umi++;
      if (umi == 9 ) {
      umi = 0;
  }
    }
   if (buttonC) {
   if (umi == 1 ) {
    buttonC = false;
    contrast--;
    setContrast();
    }
  else if (umi == 2 ) {
    buttonC = false;
    yearr--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 3 ) {
    buttonC = false;
    monthh--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 4 ) {
    buttonC = false;
    dayy--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 5 ) {
    buttonC = false;
    hourr--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 6 ) {
    buttonC = false;
    minutee--;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,secondd));
  }
  else if (umi == 7 ) {
    buttonC = false;
    rtc.adjust(DateTime(yearr,monthh,dayy,hourr,minutee,0));
  }
  else if (umi == 8 ) {
    buttonC = false;
    if (light)
      {
        light = false;
        lightOff();
        }
      else
      {
        light = true;
        lightOn();
       }
       }


}
     digitalDisplay();
}

void digitalDisplay(){
    Temp = dht.readTemperature();
    Humi = dht.readHumidity();
    DateTime now = rtc.now();

    printDigitt(now.year());
    yearr == digitt;
    printDigitt(now.month());
    dayy == digitt;
    printDigitt(now.day());
    monthh == digitt;
    printDigitt(now.hour());
    hourr == digitt;
    printDigitt(now.minute());
    minutee == digitt;
    printDigitt(now.second());
    secondd == digitt;
  // digital clock display of the time
    display.setTextSize(1);
    display.clearDisplay();
    if (umi == 1)
      {
    display.setCursor(5, 0);
    display.print(contrast);
        }
    if (umi == 8)
      {
    display.setCursor(7, 0);
    display.print("*");
        }
    display.setTextColor(BLACK, WHITE);
    display.setCursor(24, 0);
    if (umi == 2)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.year());
    display.setTextColor(BLACK, WHITE);
    display.print('/');
    if (umi == 3)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.month());
    display.setTextColor(BLACK, WHITE);
    display.print('/');
    if (umi == 4)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.day());
    if (umi == 7)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    display.setCursor(72, 20);
    printDigits(now.second());
    display.setTextSize(2);
    display.setCursor(10, 14);
    if (umi == 5)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.hour());
    display.setTextColor(BLACK, WHITE);
    display.print(':');
    if (umi == 6)
      {
    display.setTextColor(WHITE, BLACK);
        }
      else
      {
    display.setTextColor(BLACK, WHITE);
       }
    printDigits(now.minute());
    display.setTextColor(BLACK, WHITE);
    display.setCursor(0, 32);
    display.setTextSize(1);
    display.print("T");
    display.setCursor(6, 32);
    display.setTextSize(2);
    display.print(Temp);
    display.print("c");
    display.setCursor(42, 32);
    display.setTextSize(1);
    display.print("H");
    display.setCursor(48, 32);
    display.setTextSize(2);
    display.print(Humi);
    display.print("%");
    display.display();
}
void printDigits(int digits){
  // utility function for digital clock display: prints preceding
colon and leading 0
  if(digits < 10){
    display.print('0');
  display.print(digits);
       }
      else
      {
  display.print(digits);
       }
}



  void buttonAisPressed()
  {
    if (NewStateOfbuttonA != StateOfbuttonA)
  {
    if (NewStateOfbuttonA == 0)
    {
      buttonA=true;
    }
    delay(50);
  }
   StateOfbuttonA = NewStateOfbuttonA;
  }

void buttonBisPressed()
{
  if (NewStateOfbuttonB != StateOfbuttonB)
  {
    if (NewStateOfbuttonB == 0) {
      buttonB=true;
    }
    delay(50);
  }
   StateOfbuttonB = NewStateOfbuttonB;
}

void buttonCisPressed()
{
   if (NewStateOfbuttonC != StateOfbuttonC)
  {
    if (NewStateOfbuttonC == 0) {
      buttonC=true;
    }
    delay(50);
  }
   StateOfbuttonC = NewStateOfbuttonC;
}
void lightOn()
  {
    digitalWrite(8,LOW);
  }

    void lightOff()
  {
    digitalWrite(8,HIGH);
  }

  void setContrast()
  {
    display.setContrast(contrast);
    display.display();
  }
void printDigitt(int digitt){
    digitt == digitt;
       }

**Comment by geofbaum** [comment]
@siva2344 Please format your code like I had asked before. 

Your first code ran fine if you would have had all of the dependencies loaded and included at the top of the file which you are missing in both the first set of code and the second set of code. You fixed your other issue at least in the second set of code with __DATE__ and __TIME__ . Other then you not including everything that you needed and changing that, your code compiles fine. The issues you are having aren't related to the DHT library. So just as a helpful hint, you shouldn't be commenting on issues (especially closed ones) when the problem and issues you are having aren't related to the library you are commenting in. Another helpful hint, when you are trying to combine two different sets of libraries like you are make sure you look at the examples provided for each one to see what is needed to be included to make the libraries run properly. If you would do that now you'd find out exactly what you're missing from your code.

**Comment by dodeyoga** [comment]
i got this error when i try to run the code

Arduino: 1.8.7 (Windows 10), Board: "Arduino/Genuino Uno"

normal.ino.ino:7:17: error: 'DHT11' was not declared in this scope

 #define DHTTYPE DHT11

                 ^

D:\Document\Dode\Kuliah\Source Code Arduino\mix\normal.ino.ino\normal.ino.ino.ino:10:17: note: in expansion of macro 'DHTTYPE'

 dht DHT(DHTPIN, DHTTYPE);

                 ^

normal.ino.ino:21:1: error: 'WiFiClientSecure' does not name a type

 WiFiClientSecure client;

 ^

D:\Document\Dode\Kuliah\Source Code Arduino\mix\normal.ino.ino\normal.ino.ino.ino: In function 'void setup()':

normal.ino.ino:26:7: error: expected unqualified-id before '.' token

    dht.begin();

       ^

normal.ino.ino:28:3: error: 'WiFi' was not declared in this scope

   WiFi.begin(ssid, password);

   ^

normal.ino.ino:32:27: error: 'WL_CONNECTED' was not declared in this scope

   while (WiFi.status() != WL_CONNECTED) {

                           ^

normal.ino.ino:47:7: error: 'client' was not declared in this scope

   if (client.connected())

       ^

normal.ino.ino:52:3: error: 'client' was not declared in this scope

   client.flush();

   ^

exit status 1
'DHT11' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by dodeyoga** [comment]
Here is the code
#include <SoftwareSerial.h>
#include <dht.h>

SoftwareSerial ESP8266(0, 1);

/* DHT SENSOR SETUP */
#define DHTTYPE DHT11
#define DHTPIN  A0

dht DHT(DHTPIN, DHTTYPE);
float humidity, temp_f;  // Values read from 

const char* ssid = "Redmillion";
const char* password = "wkwkwk009";

//define the parameters for the IFTTT
#define HOSTIFTTT "maker.ifttt.com"
#define EVENTO "ESP_Cap_Kaki_3"
#define IFTTTKEY "cYpiVy8EhRnQom6f4Qo-z9"

WiFiClientSecure client;

void setup() {
  Serial.begin(115200);
  delay(10);
   dht.begin();
  delay(2000);
  WiFi.begin(ssid, password);
  Serial.println("");
  Serial.print("Waiting to connect to WiFi... ");

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  delay(1000);
  Serial.print("Initial Temp: ");
  Serial.println(temp_f);
  Serial.print("Initial Humi: ");
  Serial.println(humidity);

  if (client.connected())
  {
    client.stop();
  }

  client.flush();
  if (client.connect(HOSTIFTTT,443)) {
    Serial.println("Connected");
    // build the HTTP request
    String toSend = "GET /trigger/";
    toSend += EVENTO;
    toSend += "/with/key/";
    toSend += IFTTTKEY;
    toSend += "?value1=";
    toSend += temp_f;
    toSend += "&value2=";
    toSend += humidity;
    toSend += " HTTP/1.1\r\n";
    toSend += "Host: ";
    toSend += HOSTIFTTT;
    toSend += "\r\n";
    toSend += "Connection: close\r\n\r\n";
    client.print(toSend);
  }
  client.flush();
  client.stop();  
  delay(500);
  
}


void loop()
{

}

**Comment by geofbaum** [comment]
@dodeyoga 

Three things, first can you format your code to and your errors to make them easier to read. Two, this folder/file naming structure ```normal.ino.ino``` and ```normal.ino.ino.ino``` is problematic to say the least, if that type of thing hasn't caused you problems previously it probably will in the future but either way it's bad practice and when the IDE is looking for .ino files and it sees that for a file name it might cause an issue like the one you're seeing now. Lastly, you have the wrong board selected in the Arduino IDE, your errors show that you have selected Arduino/Genuino UNO as your board, but your code is clearly written for an ESP8266 board.

So first, change the IDE's selection to the correct board that you are using, and then secondly rename the files and folders, and if they aren't in the Arduino appropriate location that they should be.

For an example this is what a sample DHT file and folder location structure looks for me, and it works fine.

```C:\Users\Geof Baum\Documents\Arduino\DHT22_Test\DHT_Test.ino```

All of your errors at first glance are all related in the sense that your ```.ino``` code file can't find the appropriate files.
